#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.05 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xff23;
constexpr uint24_t FX_DATA_BYTES = 56564;

namespace Images
{
  constexpr uint24_t Keyboard_W_01 = 0x000000;
  constexpr uint16_t Keyboard_W_01_width  = 10;
  constexpr uint16_t Keyboard_W_01_height = 11;

  constexpr uint24_t Keyboard_W_02 = 0x000018;
  constexpr uint16_t Keyboard_W_02_width  = 10;
  constexpr uint16_t Keyboard_W_02_height = 11;

  constexpr uint24_t Keyboard_W_03 = 0x000030;
  constexpr uint16_t Keyboard_W_03_width  = 10;
  constexpr uint16_t Keyboard_W_03_height = 11;

  constexpr uint24_t Keyboard_W_04 = 0x000048;
  constexpr uint16_t Keyboard_W_04_width  = 10;
  constexpr uint16_t Keyboard_W_04_height = 11;

  constexpr uint24_t Keyboard_W_05 = 0x000060;
  constexpr uint16_t Keyboard_W_05_width  = 10;
  constexpr uint16_t Keyboard_W_05_height = 11;

  constexpr uint24_t Keyboard_W_06 = 0x000078;
  constexpr uint16_t Keyboard_W_06_width  = 10;
  constexpr uint16_t Keyboard_W_06_height = 11;

  constexpr uint24_t Keyboard_W_07 = 0x000090;
  constexpr uint16_t Keyboard_W_07_width  = 10;
  constexpr uint16_t Keyboard_W_07_height = 11;

  constexpr uint24_t Keyboard_W_08 = 0x0000A8;
  constexpr uint16_t Keyboard_W_08_width  = 10;
  constexpr uint16_t Keyboard_W_08_height = 11;

  constexpr uint24_t Keyboard_W_09 = 0x0000C0;
  constexpr uint16_t Keyboard_W_09_width  = 10;
  constexpr uint16_t Keyboard_W_09_height = 11;

  constexpr uint24_t Keyboard_W_10 = 0x0000D8;
  constexpr uint16_t Keyboard_W_10_width  = 10;
  constexpr uint16_t Keyboard_W_10_height = 11;

  constexpr uint24_t Keyboard_W_11 = 0x0000F0;
  constexpr uint16_t Keyboard_W_11_width  = 10;
  constexpr uint16_t Keyboard_W_11_height = 11;

  constexpr uint24_t Keyboard_W_12 = 0x000108;
  constexpr uint16_t Keyboard_W_12_width  = 10;
  constexpr uint16_t Keyboard_W_12_height = 11;

  constexpr uint24_t Keyboard_W_13 = 0x000120;
  constexpr uint16_t Keyboard_W_13_width  = 10;
  constexpr uint16_t Keyboard_W_13_height = 11;

  constexpr uint24_t Keyboard_W_14 = 0x000138;
  constexpr uint16_t Keyboard_W_14_width  = 10;
  constexpr uint16_t Keyboard_W_14_height = 11;

  constexpr uint24_t Keyboard_W_15 = 0x000150;
  constexpr uint16_t Keyboard_W_15_width  = 10;
  constexpr uint16_t Keyboard_W_15_height = 11;

  constexpr uint24_t Keyboard_W_16 = 0x000168;
  constexpr uint16_t Keyboard_W_16_width  = 10;
  constexpr uint16_t Keyboard_W_16_height = 11;

  constexpr uint24_t Keyboard_W_17 = 0x000180;
  constexpr uint16_t Keyboard_W_17_width  = 10;
  constexpr uint16_t Keyboard_W_17_height = 11;

  constexpr uint24_t Keyboard_W_18 = 0x000198;
  constexpr uint16_t Keyboard_W_18_width  = 10;
  constexpr uint16_t Keyboard_W_18_height = 11;

  constexpr uint24_t Keyboard_W_19 = 0x0001B0;
  constexpr uint16_t Keyboard_W_19_width  = 10;
  constexpr uint16_t Keyboard_W_19_height = 11;

  constexpr uint24_t Keyboard_W_20 = 0x0001C8;
  constexpr uint16_t Keyboard_W_20_width  = 10;
  constexpr uint16_t Keyboard_W_20_height = 11;

  constexpr uint24_t Keyboard_W_21 = 0x0001E0;
  constexpr uint16_t Keyboard_W_21_width  = 10;
  constexpr uint16_t Keyboard_W_21_height = 11;

  constexpr uint24_t Keyboard_W_22 = 0x0001F8;
  constexpr uint16_t Keyboard_W_22_width  = 10;
  constexpr uint16_t Keyboard_W_22_height = 11;

  constexpr uint24_t Keyboard_W_23 = 0x000210;
  constexpr uint16_t Keyboard_W_23_width  = 10;
  constexpr uint16_t Keyboard_W_23_height = 11;

  constexpr uint24_t Keyboard_W_24 = 0x000228;
  constexpr uint16_t Keyboard_W_24_width  = 10;
  constexpr uint16_t Keyboard_W_24_height = 11;

  constexpr uint24_t Keyboard_W_25 = 0x000240;
  constexpr uint16_t Keyboard_W_25_width  = 10;
  constexpr uint16_t Keyboard_W_25_height = 11;

  constexpr uint24_t Keyboard_W_26 = 0x000258;
  constexpr uint16_t Keyboard_W_26_width  = 10;
  constexpr uint16_t Keyboard_W_26_height = 11;

  constexpr uint24_t Keyboard_W_27 = 0x000270;
  constexpr uint16_t Keyboard_W_27_width  = 12;
  constexpr uint16_t Keyboard_W_27_height = 11;

  constexpr uint24_t Keyboard_W_28 = 0x00028C;
  constexpr uint16_t Keyboard_W_28_width  = 17;
  constexpr uint16_t Keyboard_W_28_height = 11;

  constexpr uint24_t Keyboard_B_01 = 0x0002B2;
  constexpr uint16_t Keyboard_B_01_width  = 10;
  constexpr uint16_t Keyboard_B_01_height = 11;

  constexpr uint24_t Keyboard_B_02 = 0x0002CA;
  constexpr uint16_t Keyboard_B_02_width  = 10;
  constexpr uint16_t Keyboard_B_02_height = 11;

  constexpr uint24_t Keyboard_B_03 = 0x0002E2;
  constexpr uint16_t Keyboard_B_03_width  = 10;
  constexpr uint16_t Keyboard_B_03_height = 11;

  constexpr uint24_t Keyboard_B_04 = 0x0002FA;
  constexpr uint16_t Keyboard_B_04_width  = 10;
  constexpr uint16_t Keyboard_B_04_height = 11;

  constexpr uint24_t Keyboard_B_05 = 0x000312;
  constexpr uint16_t Keyboard_B_05_width  = 10;
  constexpr uint16_t Keyboard_B_05_height = 11;

  constexpr uint24_t Keyboard_B_06 = 0x00032A;
  constexpr uint16_t Keyboard_B_06_width  = 10;
  constexpr uint16_t Keyboard_B_06_height = 11;

  constexpr uint24_t Keyboard_B_07 = 0x000342;
  constexpr uint16_t Keyboard_B_07_width  = 10;
  constexpr uint16_t Keyboard_B_07_height = 11;

  constexpr uint24_t Keyboard_B_08 = 0x00035A;
  constexpr uint16_t Keyboard_B_08_width  = 10;
  constexpr uint16_t Keyboard_B_08_height = 11;

  constexpr uint24_t Keyboard_B_09 = 0x000372;
  constexpr uint16_t Keyboard_B_09_width  = 10;
  constexpr uint16_t Keyboard_B_09_height = 11;

  constexpr uint24_t Keyboard_B_10 = 0x00038A;
  constexpr uint16_t Keyboard_B_10_width  = 10;
  constexpr uint16_t Keyboard_B_10_height = 11;

  constexpr uint24_t Keyboard_B_11 = 0x0003A2;
  constexpr uint16_t Keyboard_B_11_width  = 10;
  constexpr uint16_t Keyboard_B_11_height = 11;

  constexpr uint24_t Keyboard_B_12 = 0x0003BA;
  constexpr uint16_t Keyboard_B_12_width  = 10;
  constexpr uint16_t Keyboard_B_12_height = 11;

  constexpr uint24_t Keyboard_B_13 = 0x0003D2;
  constexpr uint16_t Keyboard_B_13_width  = 10;
  constexpr uint16_t Keyboard_B_13_height = 11;

  constexpr uint24_t Keyboard_B_14 = 0x0003EA;
  constexpr uint16_t Keyboard_B_14_width  = 10;
  constexpr uint16_t Keyboard_B_14_height = 11;

  constexpr uint24_t Keyboard_B_15 = 0x000402;
  constexpr uint16_t Keyboard_B_15_width  = 10;
  constexpr uint16_t Keyboard_B_15_height = 11;

  constexpr uint24_t Keyboard_B_16 = 0x00041A;
  constexpr uint16_t Keyboard_B_16_width  = 10;
  constexpr uint16_t Keyboard_B_16_height = 11;

  constexpr uint24_t Keyboard_B_17 = 0x000432;
  constexpr uint16_t Keyboard_B_17_width  = 10;
  constexpr uint16_t Keyboard_B_17_height = 11;

  constexpr uint24_t Keyboard_B_18 = 0x00044A;
  constexpr uint16_t Keyboard_B_18_width  = 10;
  constexpr uint16_t Keyboard_B_18_height = 11;

  constexpr uint24_t Keyboard_B_19 = 0x000462;
  constexpr uint16_t Keyboard_B_19_width  = 10;
  constexpr uint16_t Keyboard_B_19_height = 11;

  constexpr uint24_t Keyboard_B_20 = 0x00047A;
  constexpr uint16_t Keyboard_B_20_width  = 10;
  constexpr uint16_t Keyboard_B_20_height = 11;

  constexpr uint24_t Keyboard_B_21 = 0x000492;
  constexpr uint16_t Keyboard_B_21_width  = 10;
  constexpr uint16_t Keyboard_B_21_height = 11;

  constexpr uint24_t Keyboard_B_22 = 0x0004AA;
  constexpr uint16_t Keyboard_B_22_width  = 10;
  constexpr uint16_t Keyboard_B_22_height = 11;

  constexpr uint24_t Keyboard_B_23 = 0x0004C2;
  constexpr uint16_t Keyboard_B_23_width  = 10;
  constexpr uint16_t Keyboard_B_23_height = 11;

  constexpr uint24_t Keyboard_B_24 = 0x0004DA;
  constexpr uint16_t Keyboard_B_24_width  = 10;
  constexpr uint16_t Keyboard_B_24_height = 11;

  constexpr uint24_t Keyboard_B_25 = 0x0004F2;
  constexpr uint16_t Keyboard_B_25_width  = 10;
  constexpr uint16_t Keyboard_B_25_height = 11;

  constexpr uint24_t Keyboard_B_26 = 0x00050A;
  constexpr uint16_t Keyboard_B_26_width  = 10;
  constexpr uint16_t Keyboard_B_26_height = 11;

  constexpr uint24_t Keyboard_B_27 = 0x000522;
  constexpr uint16_t Keyboard_B_27_width  = 12;
  constexpr uint16_t Keyboard_B_27_height = 11;

  constexpr uint24_t Keyboard_B_28 = 0x00053E;
  constexpr uint16_t Keyboard_B_28_width  = 17;
  constexpr uint16_t Keyboard_B_28_height = 11;

  constexpr uint24_t Keyboard_B_Cursor = 0x000564;
  constexpr uint16_t Keyboard_B_Cursor_width  = 10;
  constexpr uint16_t Keyboard_B_Cursor_height = 11;

  constexpr uint24_t Keyboard_B_Cursor_Half = 0x000590;
  constexpr uint16_t Keyboard_B_Cursor_Half_width  = 10;
  constexpr uint16_t Keyboard_B_Cursor_Half_height = 11;

  constexpr uint24_t Correct_EN = 0x0005BC;
  constexpr uint16_t Correct_EN_width  = 46;
  constexpr uint16_t Correct_EN_height = 8;

  constexpr uint24_t Correct_FR = 0x0005EE;
  constexpr uint16_t Correct_FR_width  = 46;
  constexpr uint16_t Correct_FR_height = 8;

  constexpr uint24_t InvalidWord_EN = 0x000620;
  constexpr uint16_t InvalidWord_EN_width  = 82;
  constexpr uint16_t InvalidWord_EN_height = 12;

  constexpr uint24_t InvalidWord_FR = 0x0006C8;
  constexpr uint16_t InvalidWord_FR_width  = 118;
  constexpr uint16_t InvalidWord_FR_height = 12;

  constexpr uint24_t TooManyAttempts_EN = 0x0007B8;
  constexpr uint16_t TooManyAttempts_EN_width  = 92;
  constexpr uint16_t TooManyAttempts_EN_height = 8;

  constexpr uint24_t TooManyAttempts_FR = 0x000818;
  constexpr uint16_t TooManyAttempts_FR_width  = 108;
  constexpr uint16_t TooManyAttempts_FR_height = 8;

  constexpr uint24_t Quit_EN = 0x000888;
  constexpr uint16_t Quit_EN_width  = 70;
  constexpr uint16_t Quit_EN_height = 8;

  constexpr uint24_t Quit_FR = 0x0008D2;
  constexpr uint16_t Quit_FR_width  = 64;
  constexpr uint16_t Quit_FR_height = 8;

  constexpr uint24_t Statistics_EN = 0x000916;
  constexpr uint16_t Statistics_EN_width  = 128;
  constexpr uint16_t Statistics_EN_height = 64;

  constexpr uint24_t Statistics_FR = 0x000D1A;
  constexpr uint16_t Statistics_FR_width  = 128;
  constexpr uint16_t Statistics_FR_height = 64;

  constexpr uint24_t Pointer = 0x00111E;
  constexpr uint16_t PointerWidth  = 4;
  constexpr uint16_t PointerHeight = 5;

  constexpr uint24_t Arrow_Up = 0x001126;
  constexpr uint16_t Arrow_Up_width  = 5;
  constexpr uint16_t Arrow_Up_height = 3;

  constexpr uint24_t Arrow_Down = 0x00112F;
  constexpr uint16_t Arrow_Down_width  = 5;
  constexpr uint16_t Arrow_Down_height = 3;

  constexpr uint24_t TitleScreen_Lower = 0x001138;
  constexpr uint16_t TitleScreen_Lower_width  = 128;
  constexpr uint16_t TitleScreen_Lower_height = 35;

  constexpr uint24_t TitleScreen_L_00 = 0x0013BC;
  constexpr uint16_t TitleScreen_L_00_width  = 15;
  constexpr uint16_t TitleScreen_L_00_height = 16;

  constexpr uint24_t TitleScreen_L_01 = 0x0013DE;
  constexpr uint16_t TitleScreen_L_01_width  = 15;
  constexpr uint16_t TitleScreen_L_01_height = 16;

  constexpr uint24_t TitleScreen_L_02 = 0x001400;
  constexpr uint16_t TitleScreen_L_02_width  = 15;
  constexpr uint16_t TitleScreen_L_02_height = 16;

  constexpr uint24_t TitleScreen_L_03 = 0x001422;
  constexpr uint16_t TitleScreen_L_03_width  = 15;
  constexpr uint16_t TitleScreen_L_03_height = 16;

  constexpr uint24_t TitleScreen_E_00 = 0x001444;
  constexpr uint16_t TitleScreen_E_00_width  = 15;
  constexpr uint16_t TitleScreen_E_00_height = 16;

  constexpr uint24_t TitleScreen_E_01 = 0x001466;
  constexpr uint16_t TitleScreen_E_01_width  = 15;
  constexpr uint16_t TitleScreen_E_01_height = 16;

  constexpr uint24_t TitleScreen_E_02 = 0x001488;
  constexpr uint16_t TitleScreen_E_02_width  = 15;
  constexpr uint16_t TitleScreen_E_02_height = 16;

  constexpr uint24_t TitleScreen_E_03 = 0x0014AA;
  constexpr uint16_t TitleScreen_E_03_width  = 15;
  constexpr uint16_t TitleScreen_E_03_height = 16;

  constexpr uint24_t TitleScreen_W_00 = 0x0014CC;
  constexpr uint16_t TitleScreen_W_00_width  = 15;
  constexpr uint16_t TitleScreen_W_00_height = 16;

  constexpr uint24_t TitleScreen_W_01 = 0x0014EE;
  constexpr uint16_t TitleScreen_W_01_width  = 15;
  constexpr uint16_t TitleScreen_W_01_height = 16;

  constexpr uint24_t TitleScreen_W_02 = 0x001510;
  constexpr uint16_t TitleScreen_W_02_width  = 15;
  constexpr uint16_t TitleScreen_W_02_height = 16;

  constexpr uint24_t TitleScreen_W_03 = 0x001532;
  constexpr uint16_t TitleScreen_W_03_width  = 15;
  constexpr uint16_t TitleScreen_W_03_height = 16;

  constexpr uint24_t TitleScreen_O_00 = 0x001554;
  constexpr uint16_t TitleScreen_O_00_width  = 15;
  constexpr uint16_t TitleScreen_O_00_height = 16;

  constexpr uint24_t TitleScreen_O_01 = 0x001576;
  constexpr uint16_t TitleScreen_O_01_width  = 15;
  constexpr uint16_t TitleScreen_O_01_height = 16;

  constexpr uint24_t TitleScreen_O_02 = 0x001598;
  constexpr uint16_t TitleScreen_O_02_width  = 15;
  constexpr uint16_t TitleScreen_O_02_height = 16;

  constexpr uint24_t TitleScreen_O_03 = 0x0015BA;
  constexpr uint16_t TitleScreen_O_03_width  = 15;
  constexpr uint16_t TitleScreen_O_03_height = 16;

  constexpr uint24_t TitleScreen_R_00 = 0x0015DC;
  constexpr uint16_t TitleScreen_R_00_width  = 15;
  constexpr uint16_t TitleScreen_R_00_height = 16;

  constexpr uint24_t TitleScreen_R_01 = 0x0015FE;
  constexpr uint16_t TitleScreen_R_01_width  = 15;
  constexpr uint16_t TitleScreen_R_01_height = 16;

  constexpr uint24_t TitleScreen_R_02 = 0x001620;
  constexpr uint16_t TitleScreen_R_02_width  = 15;
  constexpr uint16_t TitleScreen_R_02_height = 16;

  constexpr uint24_t TitleScreen_R_03 = 0x001642;
  constexpr uint16_t TitleScreen_R_03_width  = 15;
  constexpr uint16_t TitleScreen_R_03_height = 16;

  constexpr uint24_t TitleScreen_D_00 = 0x001664;
  constexpr uint16_t TitleScreen_D_00_width  = 15;
  constexpr uint16_t TitleScreen_D_00_height = 16;

  constexpr uint24_t TitleScreen_D_01 = 0x001686;
  constexpr uint16_t TitleScreen_D_01_width  = 15;
  constexpr uint16_t TitleScreen_D_01_height = 16;

  constexpr uint24_t TitleScreen_D_02 = 0x0016A8;
  constexpr uint16_t TitleScreen_D_02_width  = 15;
  constexpr uint16_t TitleScreen_D_02_height = 16;

  constexpr uint24_t TitleScreen_D_03 = 0x0016CA;
  constexpr uint16_t TitleScreen_D_03_width  = 15;
  constexpr uint16_t TitleScreen_D_03_height = 16;

  constexpr uint24_t TitleScreen_X_04 = 0x0016EC;
  constexpr uint16_t TitleScreen_X_04_width  = 15;
  constexpr uint16_t TitleScreen_X_04_height = 16;

  constexpr uint24_t TitleScreen_X_05 = 0x00170E;
  constexpr uint16_t TitleScreen_X_05_width  = 15;
  constexpr uint16_t TitleScreen_X_05_height = 16;

  constexpr uint24_t TitleScreen_X_06 = 0x001730;
  constexpr uint16_t TitleScreen_X_06_width  = 15;
  constexpr uint16_t TitleScreen_X_06_height = 16;

  constexpr uint24_t TitleScreen_X_07 = 0x001752;
  constexpr uint16_t TitleScreen_X_07_width  = 15;
  constexpr uint16_t TitleScreen_X_07_height = 16;

  constexpr uint24_t TitleScreen_X_08 = 0x001774;
  constexpr uint16_t TitleScreen_X_08_width  = 15;
  constexpr uint16_t TitleScreen_X_08_height = 16;

  constexpr uint24_t TitleScreen_X_09 = 0x001796;
  constexpr uint16_t TitleScreen_X_09_width  = 15;
  constexpr uint16_t TitleScreen_X_09_height = 16;

  constexpr uint24_t TitleScreen_Y_04 = 0x0017B8;
  constexpr uint16_t TitleScreen_Y_04_width  = 15;
  constexpr uint16_t TitleScreen_Y_04_height = 16;

  constexpr uint24_t TitleScreen_Y_05 = 0x0017DA;
  constexpr uint16_t TitleScreen_Y_05_width  = 15;
  constexpr uint16_t TitleScreen_Y_05_height = 16;

  constexpr uint24_t TitleScreen_Y_06 = 0x0017FC;
  constexpr uint16_t TitleScreen_Y_06_width  = 15;
  constexpr uint16_t TitleScreen_Y_06_height = 16;

  constexpr uint24_t TitleScreen_Y_07 = 0x00181E;
  constexpr uint16_t TitleScreen_Y_07_width  = 15;
  constexpr uint16_t TitleScreen_Y_07_height = 16;

  constexpr uint24_t TitleScreen_Y_08 = 0x001840;
  constexpr uint16_t TitleScreen_Y_08_width  = 15;
  constexpr uint16_t TitleScreen_Y_08_height = 16;

  constexpr uint24_t TitleScreen_Y_09 = 0x001862;
  constexpr uint16_t TitleScreen_Y_09_width  = 15;
  constexpr uint16_t TitleScreen_Y_09_height = 16;

  constexpr uint24_t Man_Walk_L_00 = 0x001884;
  constexpr uint16_t Man_Walk_L_00_width  = 9;
  constexpr uint16_t Man_Walk_L_00_height = 18;

  constexpr uint24_t Man_Walk_L_01 = 0x0018A3;
  constexpr uint16_t Man_Walk_L_01_width  = 9;
  constexpr uint16_t Man_Walk_L_01_height = 18;

  constexpr uint24_t Man_Walk_L_02 = 0x0018C2;
  constexpr uint16_t Man_Walk_L_02_width  = 9;
  constexpr uint16_t Man_Walk_L_02_height = 18;

  constexpr uint24_t Man_Walk_L_03 = 0x0018E1;
  constexpr uint16_t Man_Walk_L_03_width  = 9;
  constexpr uint16_t Man_Walk_L_03_height = 18;

  constexpr uint24_t Man_Walk_R_00 = 0x001900;
  constexpr uint16_t Man_Walk_R_00_width  = 9;
  constexpr uint16_t Man_Walk_R_00_height = 18;

  constexpr uint24_t Man_Walk_R_01 = 0x00191F;
  constexpr uint16_t Man_Walk_R_01_width  = 9;
  constexpr uint16_t Man_Walk_R_01_height = 18;

  constexpr uint24_t Man_Walk_R_02 = 0x00193E;
  constexpr uint16_t Man_Walk_R_02_width  = 9;
  constexpr uint16_t Man_Walk_R_02_height = 18;

  constexpr uint24_t Man_Walk_R_03 = 0x00195D;
  constexpr uint16_t Man_Walk_R_03_width  = 9;
  constexpr uint16_t Man_Walk_R_03_height = 18;

  constexpr uint24_t Man_Thinking_R = 0x00197C;
  constexpr uint16_t Man_Thinking_R_width  = 9;
  constexpr uint16_t Man_Thinking_R_height = 18;

  constexpr uint24_t Man_Thinking_L = 0x00199B;
  constexpr uint16_t Man_Thinking_L_width  = 9;
  constexpr uint16_t Man_Thinking_L_height = 18;

  constexpr uint24_t Man_Word_00 = 0x0019BA;
  constexpr uint16_t Man_Word_00_width  = 20;
  constexpr uint16_t Man_Word_00_height = 4;

  constexpr uint24_t Man_Word_01 = 0x0019D2;
  constexpr uint16_t Man_Word_01_width  = 20;
  constexpr uint16_t Man_Word_01_height = 4;

  constexpr uint24_t LightBulb = 0x0019EA;
  constexpr uint16_t LightBulbWidth  = 9;
  constexpr uint16_t LightBulbHeight = 9;

}

namespace Animation
{
  constexpr uint24_t ManData_R = 0x001A00;
  constexpr uint24_t ManData_L = 0x001D0C;
}

namespace Dictionary
{
  constexpr uint24_t English_AlphaMap = 0x002018;
  constexpr uint24_t French_AlphaMap = 0x002560;
  constexpr uint24_t English_Words = 0x002AA8;
  constexpr uint24_t English_EndOfWordData = 0x00670E;
  constexpr uint24_t French_Words = 0x00670F;
  constexpr uint24_t French_EndOfWordData = 0x00DCF3;
}

