#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.04 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xff06;
constexpr uint24_t FX_DATA_BYTES = 63880;

constexpr uint24_t English_AlphaMap = 0x000000;
constexpr uint24_t French_AlphaMap = 0x000548;
constexpr uint24_t Keyboard_W_01 = 0x000A90;
constexpr uint24_t Keyboard_W_02 = 0x000AA8;
constexpr uint24_t Keyboard_W_03 = 0x000AC0;
constexpr uint24_t Keyboard_W_04 = 0x000AD8;
constexpr uint24_t Keyboard_W_05 = 0x000AF0;
constexpr uint24_t Keyboard_W_06 = 0x000B08;
constexpr uint24_t Keyboard_W_07 = 0x000B20;
constexpr uint24_t Keyboard_W_08 = 0x000B38;
constexpr uint24_t Keyboard_W_09 = 0x000B50;
constexpr uint24_t Keyboard_W_10 = 0x000B68;
constexpr uint24_t Keyboard_W_11 = 0x000B80;
constexpr uint24_t Keyboard_W_12 = 0x000B98;
constexpr uint24_t Keyboard_W_13 = 0x000BB0;
constexpr uint24_t Keyboard_W_14 = 0x000BC8;
constexpr uint24_t Keyboard_W_15 = 0x000BE0;
constexpr uint24_t Keyboard_W_16 = 0x000BF8;
constexpr uint24_t Keyboard_W_17 = 0x000C10;
constexpr uint24_t Keyboard_W_18 = 0x000C28;
constexpr uint24_t Keyboard_W_19 = 0x000C40;
constexpr uint24_t Keyboard_W_20 = 0x000C58;
constexpr uint24_t Keyboard_W_21 = 0x000C70;
constexpr uint24_t Keyboard_W_22 = 0x000C88;
constexpr uint24_t Keyboard_W_23 = 0x000CA0;
constexpr uint24_t Keyboard_W_24 = 0x000CB8;
constexpr uint24_t Keyboard_W_25 = 0x000CD0;
constexpr uint24_t Keyboard_W_26 = 0x000CE8;
constexpr uint24_t Keyboard_W_27 = 0x000D00;
constexpr uint24_t Keyboard_W_28 = 0x000D1C;
constexpr uint24_t Keyboard_B_01 = 0x000D42;
constexpr uint24_t Keyboard_B_02 = 0x000D5A;
constexpr uint24_t Keyboard_B_03 = 0x000D72;
constexpr uint24_t Keyboard_B_04 = 0x000D8A;
constexpr uint24_t Keyboard_B_05 = 0x000DA2;
constexpr uint24_t Keyboard_B_06 = 0x000DBA;
constexpr uint24_t Keyboard_B_07 = 0x000DD2;
constexpr uint24_t Keyboard_B_08 = 0x000DEA;
constexpr uint24_t Keyboard_B_09 = 0x000E02;
constexpr uint24_t Keyboard_B_10 = 0x000E1A;
constexpr uint24_t Keyboard_B_11 = 0x000E32;
constexpr uint24_t Keyboard_B_12 = 0x000E4A;
constexpr uint24_t Keyboard_B_13 = 0x000E62;
constexpr uint24_t Keyboard_B_14 = 0x000E7A;
constexpr uint24_t Keyboard_B_15 = 0x000E92;
constexpr uint24_t Keyboard_B_16 = 0x000EAA;
constexpr uint24_t Keyboard_B_17 = 0x000EC2;
constexpr uint24_t Keyboard_B_18 = 0x000EDA;
constexpr uint24_t Keyboard_B_19 = 0x000EF2;
constexpr uint24_t Keyboard_B_20 = 0x000F0A;
constexpr uint24_t Keyboard_B_21 = 0x000F22;
constexpr uint24_t Keyboard_B_22 = 0x000F3A;
constexpr uint24_t Keyboard_B_23 = 0x000F52;
constexpr uint24_t Keyboard_B_24 = 0x000F6A;
constexpr uint24_t Keyboard_B_25 = 0x000F82;
constexpr uint24_t Keyboard_B_26 = 0x000F9A;
constexpr uint24_t Keyboard_B_27 = 0x000FB2;
constexpr uint24_t Keyboard_B_28 = 0x000FCE;
constexpr uint24_t Keyboard_B_Cursor = 0x000FF4;
constexpr uint24_t Keyboard_B_Cursor_Half = 0x001020;
constexpr uint24_t Correct = 0x00104C;
constexpr uint24_t InvalidWord = 0x001134;
constexpr uint24_t TooManyAttempts = 0x0011DC;
constexpr uint24_t TitleScreen = 0x0012C4;
constexpr uint24_t Quit = 0x0016C8;
constexpr uint24_t Statistics = 0x0017B0;
constexpr uint24_t Pointer = 0x001BB4;
constexpr uint24_t English_Words = 0x001BBC;
constexpr uint24_t English_EndOfWordData = 0x006C50;
constexpr uint24_t French_Words = 0x006C51;
constexpr uint24_t French_EndOfWordData = 0x00F987;
